baseURL = "https://casiowave.github.io/"
title = "Diptanuj Sarkar"
languageCode = "en-in"
DefaultContentLanguage = "en-in" # Change this to change the site's language
theme = "hugo.386"
preserveTaxonomyNames = true
googleAnalytics = "G-8HGF7L8RSJ"

[params]
    # The name to display as main title in the home page
    mainpagetitle = "Diptanuj Sarkar - Personal Website"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "Thou shall pass!" 

    # The description of your website. It will be displayed in the home page
    mainpagedesc = "Hello, I'm Diptanuj, a 2nd Year Undergrad at IISER Kolkata. This is my website - feel free to explore! I upload content regarding stuff that I find interesting here."

    # The name to display in the copyright section in the footer
    copyrightname = "Diptanuj Sarkar"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = "https://casiowave.github.com"

    # Show the "built on Hugo" disclaimer
    showhugo = false

    # Urls for social networks
    #twitter = "https://twitter.com"
    linkedin = "https://www.linkedin.com/in/diptanuj/"
    github = "https://github.com/CasioWave"
    lastfm = "https://www.last.fm/user/CasioWave"
    rym = "https://rateyourmusic.com/~CasioWave"
    #gitlab = "https://gitlab.com/CasioWave"

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 1.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = true

[params.copyright]
    name = "Diptanuj Sarkar"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = "https://casiowave.github.io"

    # Text to go before copyright information
    #prefix = "[hugo.386 theme by Max le Fou](https://gitlab.com/maxlefou/hugo.386)"

    # Text to go between copyright and hugo disclaimer (if enabled)
    #suffix = "Example site"

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

    [[menu.main]]
    identifier = "electronics" # An unique identifier for the button
    name = "Electronics"       # A display name for the button
    url = "/electronics/"      # The path to the content. It can lead to a single page (like here)
    weight = 20          # A number to order the buttons in the navbar

    [[menu.main]]
    identifier = "quiz" # An unique identifier for the button
    name = "Quiz"       # A display name for the button
    url = "/quiz/"      # The path to the content. It can lead to a single page (like here)
    weight = 30          # A number to order the buttons in the navbar

    [[menu.main]]
    identifier = "software" # An unique identifier for the button
    name = "Software"       # A display name for the button
    url = "/software/"      # The path to the content. It can lead to a single page (like here)
    weight = 40          # A number to order the buttons in the navbar

    [[menu.main]]
    identifier = "physics" # An unique identifier for the button
    name = "Physics"       # A display name for the button
    url = "/physics/"      # The path to the content. It can lead to a single page (like here)
    weight = 15         # A number to order the buttons in the navbar

    [[menu.main]]
    identifier = "music" # An unique identifier for the button
    name = "Music"       # A display name for the button
    url = "/music/"      # The path to the content. It can lead to a single page (like here)
    weight = 50          # A number to order the buttons in the navbar

    [[menu.main]]
    identifier = "Notes"
    name = "Notes"
    url = "/notes/"
    weight = 10

    [[menu.main]]
    identifier = "Philosophy"
    name = "Philosophy"
    url = "/philosophy/"
    weight = 100

[taxonomies]
category = "categories"
tag = "tags"


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
